// Pedigree collapse: profile 8 occupies slots 8 and 10 through different parents.
export const fixture = {
    1: {
        Id: 1,
        Name: "Root-1",
        FirstName: "Alex",
        LastNameAtBirth: "Root",
        BirthDate: "1980-00-00",
        BirthLocation: "Glasgow, Scotland",
        Father: 2,
        Mother: 3,
    },
    2: {
        Id: 2,
        Name: "Irish-2",
        FirstName: "Pat",
        LastNameAtBirth: "Irish",
        BirthDate: "1940-03-02",
        DeathDate: "2020-05-01",
        BirthLocation: "County Cork, Ireland",
        Father: 4,
        Mother: 5,
    },
    3: {
        Id: 3,
        Name: "Scottish-3",
        BirthName: "Jean Scottish",
        LastNameAtBirth: "Scottish",
        BirthLocation: "Edinburgh, Midlothian",
        Father: 6,
        Mother: 7,
    },
    4: { Id: 4, Name: "Irish-4", BirthLocation: "Belfast, Northern Ireland", Father: 8, Mother: 9 },
    5: { Id: 5, Name: "UnitedKingdom-5", BirthLocation: "United Kingdom", Father: 8, Mother: 0 },
    6: { Id: 6, Name: "English-6", BirthLocation: "York, Yorkshire", Father: 10, Mother: 11 },
    7: { Id: 7, Name: "Welsh-7", BirthLocation: "Cardiff, Wales, UK", Father: 0, Mother: 0 },
    8: { Id: 8, Name: "Irish-8", BirthLocation: "Dublin, Ireland", Father: 0, Mother: 0 },
    9: { Id: 9, Name: "Irish-9", BirthLocation: "County Antrim", Father: 0, Mother: 0 },
    10: { Id: 10, Name: "English-10", BirthLocation: "London, England", Father: 0, Mother: 0 },
    11: { Id: 11, BirthNamePrivate: "Private Ancestor", Father: 0, Mother: 0 },
};
